--- 1. Retrieve the names and locations of restaurants with a rating of 4.5 or higher.
SELECT 
Name ,
City ,
Rating
FROM
Restaurants
WHERE
Rating > = 4.5

--- 2. Find the total number of orders placed by each customer. 
 SELECT 
    CustomerID, 
    COUNT(*) AS TotalOrders
FROM Orders
GROUP BY CustomerID;

--- 3. List all restaurants offering "Italian" cuisine in "Mumbai"
SELECT
RestaurantID,
Name
FROM
Restaurants
WHERE
City = 'Mumbai' and CuisineType = 'Italian'

--- 4. Calculate the total revenue generated by each restaurant from completed orders. 
SELECT 
r.RestaurantID,
r.Name,
sum(o.OrderAmount) as total_revenue 
FROM 
Restaurants r 
JOIN 
Orders o ON r.RestaurantID = o.RestaurantID
WHERE 
OrderStatus = 'Delivered'
GROUP BY 
r.RestaurantID,r.Name

--- 5. Retrieve the most recent order placed by each customer. 
SELECT 
    O.CustomerID,
    C.FirstName,
    C.LastName,
    O.OrderID,
    O.OrderDate,
    O.OrderAmount,
    O.OrderStatus
FROM Orders O
JOIN Customers C ON O.CustomerID = C.CustomerID
WHERE O.OrderDate = (
    SELECT MAX(O2.OrderDate)
    FROM Orders O2
    WHERE O2.CustomerID = O.CustomerID
);

--- 6.List customers who have not placed any orders yet.
SELECT 
c.FirstName,
c.LastName,
c.CustomerID
FROM 
Customers c 
JOIN
Orders o ON c.CustomerID = o.CustomerID
where OrderID is NULL

--- 7. Identify the most reviewed restaurants. 
SELECT
r.RestaurantID,
r.Name,
Count(re.ReviewID) as most_reviewd
FROM
Restaurants r
JOIN 
Reviews re ON r.RestaurantID = re.RestaurantID
GROUP BY 
r.RestaurantID,r.Name
order by 
most_reviewd Desc

---8. Find the most preferred payment method. 
SELECT  TOP 1
PaymentMethod,
COUNT(*) AS UsageCount
FROM Payments
GROUP BY PaymentMethod
ORDER BY UsageCount DESC

--- 9. List the top 5 restaurants by total revenue. 
SELECT TOP 5
r.Name,
Sum(o.OrderAmount) as total_revenue
FROM 
Restaurants r 
JOIN
Orders o ON r.RestaurantID = o.RestaurantID
Group by 
r.Name
Order BY
total_revenue Desc

--- 10. Show the details of all cancelled orders along with the customer's and restaurant's names. 
SELECT
    O.OrderID,
    C.FirstName AS CustomerFirstName,
    C.LastName AS CustomerLastName,
    R.Name AS RestaurantName,
    O.OrderDate,
    O.OrderAmount,
    O.OrderStatus
FROM
    Orders AS O
JOIN
    Customers AS C ON O.CustomerID = C.CustomerID
JOIN
    Restaurants AS R ON O.RestaurantID = R.RestaurantID -- Corrected typo: r.RestauatntID to r.RestaurantID
WHERE
    O.OrderStatus = 'Cancelled';


